DROP SEQUENCE IF EXISTS SEQ_USER_ID;

DROP TABLE IF EXISTS USERS;

CREATE SEQUENCE IF NOT EXISTS SEQ_USER_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS USERS (
  ID INT PRIMARY KEY,
  FIRST_NAME VARCHAR(100) NOT NULL,
  LAST_NAME VARCHAR(100) NOT NULL,
  NICK_NAME VARCHAR(50),
  BIRTHDAY DATE
);

insert into USERS values (1, 'Dummy', 'Taro', null, null);
insert into USERS values (2, 'Dummy', 'Hanako', null, null);